name: seafloor_geodesy
channels:
  - defaults
dependencies: 
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - scikit-sparse
  - julian
  - pandera
  - pyarrow
  - pydantic
  - pymap3d
  - boto3
  - botocore
  - tqdm
  - nodejs
  - nbgitpuller
  - jupyterlab
  - jupyterhub-singleuser
  - ipykernel
  - ipywidgets
  - seaborn
  - folium
  - sqlalchemy
  - tiledb
  - pip:
    - -e .
    - garpos @ git+https://github.com/EarthScope/garpos.git
    - earthscope-sdk
    - earthscope-cli
    - multipledispatch
    - multiprocessing_logging