name: seafloor_geodesy
channels:
  - defaults
  - conda-forge
dependencies: 
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn

  - julian
  - pandera
  - pyarrow
  - pydantic
  - libtiff
  - pyproj
  - pymap3d
  - boto3
  - botocore
  - tqdm
  - nodejs
  - nbgitpuller
  - jupyterlab
  - jupyterhub-singleuser
  - ipykernel
  - ipywidgets
  - seaborn
  - folium
  - sqlalchemy
  - tiledb
  - go
  - go-cgo 
  - conda-forge::gcc
  - make
  - conda-forge::tiledb
  - libstdcxx-ng
  - gcc_linux-aarch64
  - gxx_linux-aarch64
  - clang
  - pip:
    - -e .
    - scikit-sparse
    - garpos @ git+https://github.com/EarthScope/garpos.git
    - earthscope-sdk
    - earthscope-cli
    - multipledispatch
    - multiprocessing_logging
variables:
  CGO_ENABLED: 1
