name: seafloor_geodesy_linux
channels:
  - defaults
  - conda-forge
dependencies:
  # Python version & pip
  - python=3.11
  - pip

  # System dependencies that need conda for proper compilation/linking
  - scikit-sparse
  - bc
  - sqlite=3.49.1

  # Build / compiler dependencies
  - clang
  - gcc
  - gfortran
  - go
  - go-cgo
  - libstdcxx-ng
  - make
  - nodejs

  - pip:
    # Install package with all dependencies from pyproject.toml
    - -e .
    # Git dependencies not in PyPI
    # - garpos @ git+https://github.com/EarthScope/garpos.git
variables:
  CGO_ENABLED: 1
