name: seafloor_geodesy_mac
channels:
  - defaults
  - conda-forge
dependencies: 
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - gfortran
  - julian
  - pandera
  - pyarrow
  - pydantic
  - libtiff
  - pyproj
  - pymap3d
  - boto3
  - botocore
  - tqdm
  - nbgitpuller
  - jupyterlab
  - jupyterhub-singleuser
  - ipykernel
  - ipywidgets
  - seaborn
  - sqlalchemy
  - go
  - go-cgo 
  - make
  - conda-forge::tiledb
  - clang
  - scikit-sparse
  - pip:
    - -e .
    - garpos @ git+https://github.com/EarthScope/garpos.git
    - earthscope-sdk
    - earthscope-cli
    - multiprocessing_logging
variables:
  CGO_ENABLED: 1
  DYLD_LIBRARY_PATH: $CONDA_PREFIX/lib