name: seafloor_geodesy_mac
channels:
  - defaults
  - conda-forge
dependencies:
  # Python version & pip
  - python=3.11
  - pip

  # System dependencies that need conda for proper compilation/linking
  - scikit-sparse

  # Build / compiler dependencies
  - clang
  - gfortran
  - go
  - go-cgo
  - make

  - pip:
    # Install package with all dependencies from pyproject.toml
    - -e .
    # Git dependencies not in PyPI
    # - garpos @ git+https://github.com/EarthScope/garpos.git
variables:
  CGO_ENABLED: 1
