from enum import Enum
import os

class WorkingEnvironment(Enum):
    LOCAL = "LOCAL"
    GEOHUB = "GEOHUB"


WORKING_ENVIRONMENT = WorkingEnvironment.LOCAL
WORKING_ENVIRONMENT_KEY = "WORKING_ENVIRONMENT"

S3_SYNC_BUCKET_KEY = "S3_SYNC_BUCKET"
S3_SYNC_BUCKET = None

MAIN_DIRECTORY_GEOHUB_KEY = "MAIN_DIRECTORY_GEOHUB"
MAIN_DIRECTORY_GEOHUB = None